//tealium universal tag - utag.296 ut4.0.202109280949, Copyright 2021 Tealium.com Inc. All Rights Reserved.
var uetq=uetq||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.initialized=false;u.map={"bing_tag_id":"tagid","page_type":"ecomm_pagetype","product_id":"ecomm_prodid"};u.extend=[function(a,b,c,d,e,f,g){if(1){d=b['country'];if(typeof d=='undefined')return;c=[{'(AU|NZ)':'4039429'},{'(UK|DE|FR|IT|ES|NL|BE|DK|PL|PT|CZ|SK|NO|CH|SE|FI|GR|IE|AT)':'36000031'},{'US':'5713812'},{'(AR|CL|CO|MX|PE)':'4056620'},{'CA':'18008616'},{'IN':'56210161'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){g=new RegExp(f,'i');if(g.test(d)){b['bing_tag_id']=c[e][f];m=true};};if(m)break};if(!m)b['bing_tag_id']='';}},function(a,b,c,d,e,f,g){if(1){d=b['page_type'];if(typeof d=='undefined')return;c=[{'HOME':'home'},{'CLP':'category'},{'SLP':'category'},{'PLP':'category'},{'SEARCH':'searchresults'},{'PDP':'product'},{'SHOPPING CART':'cart'},{'CHECKOUT':'purchase'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['page_type']=c[e][f];m=true};};if(m)break};if(!m)b['page_type']='other';}},function(a,b){if(b.page_type==='PLP'||b.page_type==='CLP'||b.page_type=='SEARCH'){b._cprod='';}},function(a,b){try{if(1){if(a=='link'&&b.bv_event){return false;}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"base_url":"//bat.bing.com/bat.js","tagid":"","ec":"","ea":"","el":"","ev":"","gv":"","order_subtotal":b._corder!=""?b._csubtotal:"","order_id":b.order_id,"_ccurrency":b._ccurrency};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.loader_cb=function(){if(!u.initialized){var o={ti:u.data.tagid};o.q=uetq;uetq=new UET(o);uetq.push("pageLoad");}
if(a=='view'&&u.initialized){uetq.push('event','page_view',{page_path:document.location.pathname});}
u.initialized=true;g={};if(u.data.ec){g.ec=u.data.ec;}
if(u.data.ea){g.ea=u.data.ea;}
if(u.data.el){g.el=u.data.el;}
if(u.data.ev){g.ev=u.data.ev;}
if(u.data.ecomm_pagetype){g.ecomm_pagetype=u.data.ecomm_pagetype;}
if(u.data.ecomm_prodid){g.ecomm_prodid=u.data.ecomm_prodid;}
u.data.gv=u.data.gv||u.data.order_subtotal;g.gc=u.data.currency||u.data._ccurrency;if(u.data.gv){var gv=parseFloat(u.data.gv,10);if(isNaN(gv)===false){g.gv=gv;}}
uetq.push(g);};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":"utag_296"});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);}("296","adidas.adidasglobal"));}catch(error){utag.DB(error);}
var uetq=uetq||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.initialized=false;u.map={"bing_tag_id":"tagid","page_type":"ecomm_pagetype","product_id":"ecomm_prodid"};u.extend=[function(a,b,c,d,e,f,g){if(1){d=b['country'];if(typeof d=='undefined')return;c=[{'(AU|NZ)':'4039429'},{'(UK|DE|FR|IT|ES|NL|BE|DK|PL|PT|CZ|SK|NO|CH|SE|FI|GR|IE|AT)':'36000031'},{'US':'5713812'},{'(AR|CL|CO|MX|PE)':'4056620'},{'CA':'18008616'},{'IN':'56210161'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){g=new RegExp(f,'i');if(g.test(d)){b['bing_tag_id']=c[e][f];m=true};};if(m)break};if(!m)b['bing_tag_id']='';}},function(a,b,c,d,e,f,g){if(1){d=b['page_type'];if(typeof d=='undefined')return;c=[{'HOME':'home'},{'CLP':'category'},{'SLP':'category'},{'PLP':'category'},{'SEARCH':'searchresults'},{'PDP':'product'},{'SHOPPING CART':'cart'},{'CHECKOUT':'purchase'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['page_type']=c[e][f];m=true};};if(m)break};if(!m)b['page_type']='other';}},function(a,b){if(b.page_type==='PLP'||b.page_type==='CLP'||b.page_type=='SEARCH'){b._cprod='';}},function(a,b){try{if(1){if(a=='link'&&b.bv_event){return false;}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"base_url":"//bat.bing.com/bat.js","tagid":"","ec":"","ea":"","el":"","ev":"","gv":"","order_subtotal":b._corder!=""?b._csubtotal:"","order_id":b.order_id,"_ccurrency":b._ccurrency};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.loader_cb=function(){if(!u.initialized){var o={ti:u.data.tagid};o.q=uetq;uetq=new UET(o);uetq.push("pageLoad");}
if(a=='view'&&u.initialized){uetq.push('event','page_view',{page_path:document.location.pathname});}
u.initialized=true;g={};if(u.data.ec){g.ec=u.data.ec;}
if(u.data.ea){g.ea=u.data.ea;}
if(u.data.el){g.el=u.data.el;}
if(u.data.ev){g.ev=u.data.ev;}
if(u.data.ecomm_pagetype){g.ecomm_pagetype=u.data.ecomm_pagetype;}
if(u.data.ecomm_prodid){g.ecomm_prodid=u.data.ecomm_prodid;}
u.data.gv=u.data.gv||u.data.order_subtotal;g.gc=u.data.currency||u.data._ccurrency;if(u.data.gv){var gv=parseFloat(u.data.gv,10);if(isNaN(gv)===false){g.gv=gv;}}
uetq.push(g);};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":"utag_296"});}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);}("296","adidas.adidasglobal"));}catch(error){utag.DB(error);}
